### ISSUE TITLE
Command fails with "TypeError: fdopen() takes no keyword arguments" on Python 2.7

### ISSUE THREAD

**Issue by s3rvac** [s3rvac/git-edit-index#3]
When `git edit-index` is run via Python 2.7, it fails with the following error:
```
Traceback (most recent call last):
  File "~/bin/git-edit-index", line 400, in <module>
    main(sys.argv)
  File "~/bin/git-edit-index", line 390, in main
    new_index = edit_index(orig_index)
  File "~/bin/git-edit-index", line 202, in edit_index
    with os.fdopen(tmp_fd, mode='w') as f:
TypeError: fdopen() takes no keyword arguments
```
It seems that [`os.fdopen()`](https://docs.python.org/2.7/library/os.html#os.fdopen) on Python 2.7 does not support passing `mode` via a keyword argument. The use of `os.fdopen()` was introduced in 8e360aac83056b9c1611b4cf60d153bee6b3ece2. Unit tests were unable to catch this as we mock `os.fdopen()` in there.

**Comment by s3rvac** [comment]
Fixed in 0adf3b836382647500d0a3873b8b759969c36b81. In Python 2.7, `os.fdopen()` does not support passing `mode` as a keyword
argument, so we have to pass it as a positional argument.
